version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./${MOUNT_DIR}:/app/${MOUNT_DIR}
    env_file: .env
    stdin_open: true  # Keep stdin open
    tty: true         # Allocate a pseudo-TTY
    ports:
      - "${EXPOSE_PORT}:${PORT}"
    restart: unless-stopped