version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./${DB_NAME}:${APP_DIR}/${DB_NAME}
    env_file: .env
    stdin_open: true  # Keep stdin open
    tty: true         # Allocate a pseudo-TTY
    ports:
      - "${EXPOSE_PORT}:${PORT}"
    restart: unless-stopped